CREATE OR REPLACE TABLE BusinessLocationCustomer (
    PartyId VARCHAR(18) NOT NULL,
    BusinessUnitCd VARCHAR(5) NOT NULL,
    BusinessLocationCd VARCHAR(4) NOT NULL,
    ValidityPeriodStartDttm TIMESTAMP_LTZ,
    ValidityPeriodEndDttm TIMESTAMP_LTZ, 
    BusinessLocationCdSource VARCHAR(20),
    LocalCustomerId VARCHAR(100),
    LocalAccountOfficerLogonid VARCHAR(15),
    LocalAcctOfficerLogonidSource VARCHAR(15),
    OprnlIntrnlOrganizationUnitCd VARCHAR(20),
    OprnlIntrnlOrgnUnitCdSource VARCHAR(50),
    CountryCd VARCHAR(2),
    CountryCdSource VARCHAR(20),
    BusinessUnitCdSource VARCHAR(20),
    DataSourceCd VARCHAR(10) NOT NULL,
    DataProviderCd VARCHAR(10),
    DataProviderChainTxt VARCHAR(80),
    FirstRegisteredDttm TIMESTAMP_TZ,
    LastChangedDttm TIMESTAMP_TZ,
    LastChangedReasonCd VARCHAR(10),
    LastChangedByLogonId VARCHAR(15),
    DILastChangedFromSRCInd VARCHAR(1) NOT NULL,
    DIDifferCd CHAR(1) NOT NULL,
    DIParcelId VARCHAR(60) NOT NULL,
    DIParcelProducedDttm TIMESTAMP_TZ NOT NULL,
    DILastBusinessDttm TIMESTAMP_TZ NOT NULL,
    DIVersionSeq INTEGER NOT NULL,
    LTStatusCd CHAR(1) NOT NULL,
    LTInsertToLoadTableDttm TIMESTAMP_TZ NOT NULL,
    LTTargetTableUpdatedDttm TIMESTAMP_TZ,
    LTSkipRowReasonCd CHAR(1) NOT NULL DEFAULT '0',
CONSTRAINT BusinessLocationCustomerUSI1 UNIQUE ( PartyId ,BusinessUnitCd ,BusinessLocationCd ,DataSourceCd ,DIParcelId ,DIVersionSeq ));